# Generated by Django 2.0.7 on 2021-02-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='plant',
            new_name='plants',
        ),
    ]
