# Generated by Django 2.0.7 on 2021-03-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20210206_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='last_watered',
            field=models.DateField(),
        ),
    ]
