# Generated by Django 3.1.7 on 2021-03-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20210304_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='event_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
